stages:
  data_ingestion:
    cmd: python src/pipeline/stage01_data_ingestion.py
    deps:
    - src/config.yaml
    - src/pipeline/stage01_data_ingestion.py
    outs:
    - data/raw/winequality-red.csv

  data_validation:
    cmd: python src/pipeline/stage02_data_validation.py
    deps:
    - src/config.yaml
    - data/raw/winequality-red.csv
    - src/pipeline/stage02_data_validation.py
    outs:
    - data/status.txt
  data_transformation:
    cmd: python src/pipeline/stage03_data_transformation.py
    deps:
    - src/config.yaml
    - data/raw/winequality-red.csv
    - data/status.txt
    - src/pipeline/stage03_data_transformation.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
